version: "3.8"
services:
  timelogger_xampp:
    image: digitme2/timelogger
    ports:
        - "80:80"
        - "3306:3306"
    volumes:
      - type: volume
        source: timelogger_db_vol
        target: /opt/lampp/var/mysql

volumes:
  timelogger_db_vol:
  