version: "3.8"
services:
  timelogger_xampp:
    image: digitme2/timelogger
    ports:
        - "80:80"
        - "3307:3306"
    volumes:
      - type: volume
        source: timelogger_db_vol
        target: /opt/lampp/var/mysql 
      - type: volume
        source: timelogger_jobQrCodes_vol
        target: /opt/lampp/htdocs/timelogger/generatedJobQrCodes
      - type: volume
        source: timelogger_userQrCodes_vol
        target: /opt/lampp/htdocs/timelogger/generatedUserQrCodes
      - type: volume
        source: timelogger_productQrCodes_vol
        target: /opt/lampp/htdocs/timelogger/generatedProductQrCodes
      - type: volume
        source: timelogger_stoppagesQrCodes_vol
        target: /opt/lampp/htdocs/timelogger/generatedStoppagesQrCodes

volumes:
  timelogger_db_vol:
  timelogger_jobQrCodes_vol:
  timelogger_userQrCodes_vol:
  timelogger_productQrCodes_vol:
  timelogger_stoppagesQrCodes_vol:
  
